version: '3.7'

services:

    postgres:
        image: "postgres:12-alpine"
        environment:
            POSTGRES_USER: hauki
            POSTGRES_PASSWORD: hauki
            POSTGRES_DB: hauki
        ports:
            - "127.0.0.1:5555:5432"
        volumes:
            - postgres-data-volume:/var/lib/postgresql/data

    dev:
        image: hauki_dev
        depends_on:
            - postgres
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: development
        environment:
            - DEBUG=true
            - DATABASE_URL=postgres://hauki:hauki@postgres/hauki
            - WAIT_FOR_IT_ADDRESS=postgres:5432
        # Uncomment this if you want to configure development instance with the external file
        # env_file:
        #     - config_dev.env
        volumes:
            - .:/hauki:cached
            - $HOME/maintenance:/maintenance
            - $HOME/hauki_logs:/logs
        command: ["start_django_development_server"]
        ports:
            - "127.0.0.1:8000:8000"

    deploy:
        image: hauki
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: production


volumes:
        postgres-data-volume:

networks:
    default:
        name: helsinki
